using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
namespace webzpitest.Models
{
     [Table("applicationsdlp")]
    public class Applicationsdlp
    {
        [Key]
        public decimal Code { get; set; }
        public decimal DepartmentCode { get; set; }
        public decimal? UserRoleCode { get; set; }
        public decimal? BatchCode { get; set; }
        public decimal? CourseTypeCode { get; set; }
        public decimal? CourseCode { get; set; }
        public decimal? CourseCode1 { get; set; }
        public decimal? Feeplanrevised { get; set; }
        public decimal? FeePlanCode { get; set; }
        public decimal? ExamCentreCode { get; set; }
        public decimal? PaymentModeCode { get; set; }
        public decimal? SourceInfoCode { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Gender { get; set; }
        public decimal? LanguageID { get; set; }
        public string Correspondance { get; set; }
        public string HomeAddress1 { get; set; }
        public string HomeAddress2 { get; set; }
        public string HomeAddress3 { get; set; }
        public string HomeAddress4 { get; set; }
        public string HomeNearPO { get; set; }
        public decimal? HomeCity { get; set; }
        public decimal? OfficeCity { get; set; }
        public decimal? HomeStateCode { get; set; }
        public decimal? HomeCountryCode { get; set; }
        public decimal? OfficeCountryCode { get; set; }
        public string HomePincode { get; set; }
        public string HomeTelNo { get; set; }
        public string HomeMobileNo { get; set; }
        public string HomeEMail { get; set; }
        public string OfficeEMail { get; set; }
        public int? ExamCode { get; set; }
        public string Examothers { get; set; }
        public string Board { get; set; }
        public string School { get; set; }
        public int? PassYear { get; set; }
        public decimal? GradeCode { get; set; }
        public string Organization { get; set; }
        public int? Duration { get; set; }
        public string Designation { get; set; }
        public string WorkNature { get; set; }
        public string OfficeTelNo { get; set; }
        public int? TotalDuration { get; set; }
        public decimal? WelCourse { get; set; }
        public decimal? WelYear { get; set; }
        public string WelRollNo { get; set; }
        public decimal? WelGrade { get; set; }
        public string Prefix { get; set; }
        public string AppNo { get; set; }
        public DateTime? AppDate { get; set; }
        public decimal? Amount { get; set; }
        public decimal? Amount1 { get; set; }
        public decimal? Amount2 { get; set; }
        public decimal? Amount3 { get; set; }
        public decimal? AddlAmount { get; set; }
        public string DDBank { get; set; }
        public string DDBranch { get; set; }
        public string DDNo { get; set; }
        public string Class { get; set; }
        public DateTime? DDDate { get; set; }
        public string ChallanNo { get; set; }
        public DateTime? ChallanDate { get; set; }
        public decimal? TransactionTypeCode { get; set; }
        public string AdmissionStatus { get; set; }
        public bool? EntryStatus { get; set; }
        public bool ReceiptStatus { get; set; }
        public string FeeStatus { get; set; }
        public string AdmissionNo { get; set; }
        public DateTime? AdmissionDate { get; set; }
        public decimal? SpeciCode { get; set; }
        public decimal? PCPCentreCode { get; set; }
        public bool ActiveInactive { get; set; }
        public decimal? LastModUserCode { get; set; }
        public DateTime? LastModDate { get; set; }
        public decimal? PrefExmCenCode { get; set; }
        public string OfficeAddress1 { get; set; }
        public string OfficeAddress2 { get; set; }
        public string OfficeAddress3 { get; set; }
        public string OfficeAddress4 { get; set; }
        public string OfficeMobileNo { get; set; }
        public string OfficePincode { get; set; }
        public decimal? OfficeStateCode { get; set; }
        public decimal? DivisionCode { get; set; }
        public decimal? LocationCode { get; set; }
        public decimal? Exp2CRM { get; set; }
        public string WaiverList { get; set; }
        public string WaivedSubjects { get; set; }
        public decimal? EligibilityCode { get; set; }
        public decimal? ExamYearCode { get; set; }
        public decimal? CurrentCodeForMPGD { get; set; }
        public string PrevAdmissionno { get; set; }
        public bool CourseCompletionStatus { get; set; }
        public bool? NotwritingExams { get; set; }
        public decimal? ICICIRollNo { get; set; }
        public string Password1 { get; set; }
        public string ReferenceNo { get; set; }
        public bool? Appsubmitted { get; set; }
        public decimal? IndustryCode { get; set; }
        public string IndustryOthers { get; set; }
        public string IndustryType { get; set; }
        public byte? CurrentExp { get; set; }
        public byte? TotExpInMonths { get; set; }
        public byte? TotCurrentExpInMonths { get; set; }
        public bool? PresentWorkorNot { get; set; }
        public bool? AllowAdmission { get; set; }
        public decimal? Prefadmissioncentercode { get; set; }
        public string Educationothers { get; set; }
        public bool? Internet { get; set; }
        public decimal? NetConnectionType { get; set; }
        public bool? BlockResult { get; set; }
        public string DocList { get; set; }
        public string DocNames { get; set; }
        public decimal? FranchiseeId { get; set; }
        public int? AppNoStatus { get; set; }
        public decimal? Pgwcode { get; set; }
        public decimal? SourceCode { get; set; }
        public decimal? UserCode { get; set; }
        public bool? subjectsviewed { get; set; }
        public decimal? regioncode { get; set; }
        public string OldAutoAppNo { get; set; }
        public decimal? MTAmount { get; set; }
        public string MTDDno { get; set; }
        public decimal? MTPaymode { get; set; }
        public string MTBank { get; set; }
        public DateTime? MTDDDate { get; set; }
        public string MTChallanno { get; set; }
        public string RemarkForactiveInActive { get; set; }
        public string SAP_Code { get; set; }
        public string CardHoldername { get; set; }
        public decimal? cardType { get; set; }
        public int? Repcode { get; set; }
        public string fb { get; set; }
        public string linkedin { get; set; }
        public string twitter { get; set; }
        public string appnoallocate { get; set; }
        public string NatureIndus { get; set; }
        public int? sem1 { get; set; }
        public int? sem2 { get; set; }
        public int? sem3 { get; set; }
        public int? sem4 { get; set; }
        public string ParentsMobileNo { get; set; }
        public string ParentMailid { get; set; }
        public string ParentName { get; set; }
        public bool? validforPlacement { get; set; }
        public int? pgwayCode { get; set; }
        public string transactionID { get; set; }
        public int? GrnoForAuto { get; set; }
        public DateTime? transactiondate { get; set; }
        public int? flag { get; set; }
        public string BackendRemark { get; set; }
        public DateTime? ONLDate { get; set; }
        public DateTime? OriginalAdmiDate { get; set; }
    }
}